### ISSUE TITLE
message-model doesn't support variables?

### ISSUE THREAD

**Issue by Ignasimg** [cronvel/spellcast#1]
I was trying to figure out how to work with spellcast when I came up with what looks like a bug

```
[[doctype spellcast/book]]

[message-model bob]
    before: "Bob says: "

[chapter intro]
    [scene village]
        [input $name]
            name
        [m bob] Hello ${name}
        [message]
            $> Hello ${name}
        [end]
```

It will print "Bob says: Hello ${name}" without any substitution.
message works fine.

**Comment by cronvel** [comment]
Hi @Ignasimg,
There is no bug, template string are introduced with `$>`.
Your `[m bob]` tag is using the implicit string, which is never a template.
Replace `[m bob] Hello ${name}` by `[m bob] $> Hello ${name}` and it will work.

I'm curious to know how you found `Spellcast` and what kind of project are you creating ;)

**Comment by cronvel** [comment]
Hi @Ignasimg,
Just replace `[m bob] Hello ${name}` with `[m bob] $> Hello ${name}`.
Implicit string are always regular (non-template) string.
A template string is introduced by `$>`.

BTW I'm curious to know what kind of project you want to create with Spellcast! ;)

**Comment by cronvel** [comment]
@Ignasimg Any feedback?

**Comment by Ignasimg** [comment]
Thank you for your answer!

I came from your blog, and was triggered by the name.

So far I'm just experimenting and trying to find out how things work. But looks really promising!

I'll reach you back if I got any suggestion or issue.

**Comment by cronvel** [comment]
@Ignasimg Ok, thanks!
